# toml-docs-start main
title = "Kho Sàn Gỗ Nhập khẩu Tại Hà Nội"
copyright = "Copyright © 2025"
enableGitInfo = false
# toml-docs-end main

# additional settings
baseURL = "https://khovansango.com/"
canonifyURLs = false
enableEmoji = true
enableRobotsTXT = true
enableInlineShortcodes = true
summaryLength = 20

# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

timeout = "1800s"

# toml-docs-start language
languageCode = "vi-VN"
defaultContentLanguage = "vi"
defaultContentLanguageInSubdir = false
# toml-docs-end language

[outputFormats]
  [outputFormats.server]
    mediaType = "application/toml"
    baseName = "server"
    isPlainText = true
    notAlternative = true
    permalinkable = true
    root = true
  [outputFormats.netlify]
    mediaType = "application/toml"
    baseName = "netlify"
    isPlainText = true
    notAlternative = true
    permalinkable = true
    root = true
  [outputFormats.REDIR]
    mediaType = "text/netlify"
    baseName = "_redirects"
    isPlainText = true
    notAlternative = true
  [outputFormats.XML]
    isPlainText = false
    mediaType = "application/xml"
    isHtml = false
    noUgly = true
    permalinkable = false
    name = "xml"

[mediaTypes."text/netlify"]
delimiter = ""

[outputs]
home = ["HTML", "RSS", "REDIR", "server"]

[build]
  writeStats = true
  
[taxonomies]
  tag = 'tags'
  series = 'series'

[pagination]
  pagerSize = 15

[privacy]
  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]
  [services.instagram]
    disableInlineCSS = true
  [services.twitter]
    disableInlineCSS = true
  # [services.googleAnalytics]
    # ID = "G-xxxxxxxxxx"

[minify]
  [minify.tdewolff.js]
    keepVarNames = true
    precision = 0
    version = 2022
  [minify.tdewolff.html]
    keepWhitespace = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.136.3"
  [[module.mounts]]
    source = "archetypes"
    target = "archetypes"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "content"
    target = "content"
  [[module.mounts]]
    source = "data"
    target = "data"
  [[module.mounts]]
    source = "i18n"
    target = "i18n"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.mounts]]
    source = "static"
    target = "static"
# toml-docs-start modules
  [[module.imports]]
    path = "github.com/gethinode/mod-bootstrap"
    version = "v1.3.2"
  [[module.imports]]
    path = "github.com/gethinode/mod-utils/v2"
    version = "v2.10.0"
# toml-docs-end modules
[segments]
  [segments.headers]
    [[segments.headers.includes]]
       kind = '{home}'
       output = '{server}'
# xử lý ảnh

