[[main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Dự Án"
  weight = 20
[[main]]
  parent = "Dự Án"
  name = "Thiết Kê"
  pageRef = "/thiet-ke/"
  weight = 21

[[main]]
  parent = "Dự Án"
  name = "Thi Công"
  pageRef = "thi-cong"
  weight = 22

[[main]]
  name = "Phòng Khách"
  weight = 30
[[main]]
  parent = "Phòng Khách"
  name = "Sofa"
  pageRef = "#"
  weight = 31

[[main]]
  parent = "Phòng Khách"
  name = "Bàn Trà"
  pageRef = "#"
  weight = 32

[[main]]
  parent = "Phòng Khách"
  name = "Kệ Tivi"
  pageRef = "#"
  weight = 33

[[main]]
  name = "Phòng Ngủ"
  weight = 40
[[main]]
  parent = "Phòng Ngủ"
  name = "Giường"
  pageRef = "#"
  weight = 41

[[main]]
  parent = "Phòng Ngủ"
  name = "Tủ Áo"
  pageRef = "#"
  weight = 42

[[main]]
  parent = "Phòng Ngủ"
  name = "Bàn Trang Điểm"
  pageRef = "#"
  weight = 43

[[main]]
  name = "Phòng Bếp"
  weight = 50
[[main]]
  parent = "Phòng Bếp"
  name = "Bàn Ăn"
  pageRef = "#"
  weight = 51

[[main]]
  parent = "Phòng Bếp"
  name = "Tủ Bếp"
  pageRef = "#"
  weight = 52

[[main]]
  name = "Thiết Kế"
  weight = 60
[[main]]
  parent = "Thiết Kế"
  name = "Nội Thất Biệt Thự"
  pageRef = "#"
  weight = 61

[[main]]
  parent = "Thiết Kế"
  name = "Nội Thất Nhà Phố"
  pageRef = "#"
  weight = 62
  
[[main]]
  parent = "Thiết Kế"
  name = "Nội Thất Chung Cư"
  pageRef = "#"
  weight = 62

[[main]]
  name = "Thi Công"
  weight = 70
[[main]]
  parent = "Thi Công"
  name = "Nội Thất Biệt Thự"
  pageRef = "#"
  weight = 71

[[main]]
  parent = "Thi Công"
  name = "Nội Thất Nhà Phố"
  pageRef = "#"
  weight = 72
  
[[main]]
  parent = "Thi Công"
  name = "Nội Thất Chung Cư"
  pageRef = "#"
  weight = 72

[[main]]
  name = "Tin Tức"
  weight = 80
[[main]]
  parent = "Tin Tức"
  name = "Kinh Nghiệm"
  pageRef = "#"
  weight = 81

[[main]]
  parent = "Tin Tức"
  name = "Cẩm Nang"
  pageRef = "#"
  weight = 82
  
[[main]]
  parent = "Tin Tức"
  name = "Chia Sẻ"
  pageRef = "#"
  weight = 82
  
[[main]]
  parent = "Tin Tức"
  name = "Phong Thuỷ"
  pageRef = "#"
  weight = 82

[[main]]
  name = "Tư Vấn"
  pageRef = "#"
  weight = 80

[[main]]
  name = "Dự Án"
  pageRef = "#"
  weight = 80

[[main]]
  name = "Xưởng"
  pageRef = "/lien-he/"
  weight = 90

[[main]]
  name = "Liên Hệ"
  pageRef = "/lien-he/"
  weight = 91

[[social]]
  name = "LinkedIn"
  pre = "fab linkedin"
  url = "https://linkedin.com"
  weight = 80

[[social]]
  name = "X"
  pre = "fab fa-square-x-twitter"
  url = "https://x.com/khovansango"
  weight = 30
[[social]]
  name = "Pinterest"
  pre = "fab fa-pinterest"
  url = "https://www.pinterest.com/khovansangocom/"
  weight = 40

[[social]]
  name = "Facebook"
  pre = "fab fa-facebook"
  url = "https://www.facebook.com/khovansangonhapkhau/"
  weight = 50

[[social]]
  name = "Instagram"
  pre = "fab fa-instagram"
  url = "https://www.instagram.com/khosangonhapkhau"
  weight = 60

[[social]]
  name = "TikTok"
  pre = "fab fa-tiktok"
  url = "https://tiktok.com"
  weight = 70

[[footer]]
  name = "Sản Phẩm"
  weight = 10

[[footer]]
  parent = "Sản Phẩm"
  name = "Sofa gỗ óc chó"
  pageRef = "/"
  weight = 11

[[footer]]
  parent = "Sản Phẩm"
  name = "Giường gỗ óc chó"
  pageRef = "#"
  weight = 13

[[footer]]
  parent = "Sản Phẩm"
  name = "Bàn ăn gỗ óc chó"
  pageRef = "#"
  weight = 14

[[footer]]
  parent = "Sản Phẩm"
  name = "Tủ bếp gỗ óc chó"
  pageRef = "#"
  weight = 15
 
[[footer]]
  parent = "Sản Phẩm"
  name = "Tủ Áo"
  pageRef = "#"
  weight = 16

[[footer]]
  parent = "Sản Phẩm"
  name = "Kệ Tivi"
  pageRef = "#"
  weight = 17

[[footer]]
  name = "Dịch Vụ"
  weight = 20
  
[[footer]]
  parent = "Dịch Vụ"
  name = "Thiết Kế Biệt Thự"
  pageRef = "#"

[[footer]]
  parent = "Dịch Vụ"
  name = "Thiết Kế Chung Cư"
  pageRef = "#"
 
[[footer]]
  parent = "Dịch Vụ"
  name = "Thiết Kế Nhà Phố"
  pageRef = "#"
  
[[footer]]
  parent = "Dịch Vụ"
  name = "Thi Công Biệt Thự"
  pageRef = "#"

[[footer]]
  parent = "Dịch Vụ"
  name = "Thi Công Chung Cư"
  pageRef = "#"

[[footer]]
  parent = "Dịch Vụ"
  name = "Thi Công Nhà Phố"
  pageRef = "#"

[[footer]]
  name = "Chính Sách"
  weight = 30

  [[footer]]
  parent = "Chính Sách"
  name = "Bảo Mật"
  url = "chinh-sach/chinh-sach-bao-mat"
  weight = 31

[[footer]]
  parent = "Chính Sách"
  name = "Thanh Toán"
  url = "chinh-sach/chinh-sach-thanh-toan"
  weight = 32

[[footer]]
  parent = "Chính Sách"
  name = "Vận Chuyển"
  url = "chinh-sach/chinh-sach-van-chuyen"
  weight = 33

[[footer]]
  parent = "Chính Sách"
  name = "Bảo Hành"
  url = "chinh-sach/chinh-sach-bao-hanh"
  weight = 34

[[footer]]
  parent = "Chính Sách"
  name = "Đổi Trả"
  pageRef = "chinh-sach/chinh-sach-doi-tra"
  weight = 35

  [[footer]]
  parent = "Chính Sách"
  name = "Bảo Mật"
  url = "chinh-sach/chinh-sach-dai-ly"
  weight = 31